mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: on
    jdbc-type-for-null: 'null'
  type-handlers-package: com.ranranx.aolie.core.ds.dataoperator.mybatis
logging:
  pattern:
    console: "%C:%L %m%n"
#pagehelper.
pagehelper:
  autoDialect: true
  closeConn: true
  hello: \u4F60\u597D
  nihao: Hello
  offset-as-page-num: false
aolie:
  uploadpath: "g:/affix_location"
server:
  port: 8080
spring:
  jackson:
    # 全局设置@JsonFormat的格式pattern
    date-format: yyyy-MM-dd
    # 当地时区
    locale: zh
    # 设置全局时区
    time-zone: GMT+8

